# Exported from:        http://Ponnivalavan:5516/
# Release version:      25.3.0-SNAPSHOT
# Date created:         Thu Jul 17 18:42:34 IST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Notifications.yaml
