# Exported from:        http://Ponnivalavan:5516/
# Release version:      25.1.7-1130.800
# Date created:         Wed Dec 03 15:15:33 IST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: container_argocd
spec:
- pattern: dsds
  description: sdsds
  plannedDuration: 720
  stages:
  - stage: New Stage
  autoComplete: true
